### ISSUE TITLE
1.0 milestones

### ISSUE THREAD

**Issue by Xaeroxe** [Xaeroxe/c-closures-rs#3]
I feel it's healthy for a sub 1.0 project to have a defined list of things that need to happen before it can go 1.0. So here's the list for this repository.

- [x] Figure out a general way to permit multiple arguments to closures that doesn't significantly hamper performance. (Bonus points if it reduces the amount of boxing in this crate)
- [x] Type check arguments on C/C++ side without significantly hampering performance.
  - [x] ~~Provide some kind of compile time mapping between C/C++ classes/structs and Rust structs, then use this mapping to validate call sites (or to generate a type checked function signature).~~ Not necessary, rust bindgen handles this well enough.

There's a general theme here. We need to start doing C/C++ code generation in addition to Rust code generation. Maybe the template system would be useful here? There's a massive amount of ways to do C/C++ builds, and ideally said code generation system would be able to plug into all of them.
